export const BOOK_ROOM = 'BOOK_ROOM';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const ADD_ROOM = 'ADD_ROOM';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_BEGINS = 'FETCH_ROOMS_BEGINS';
export const FETCH_ROOMS_FAILURE = 'FETCH_ROOMS_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
